### ISSUE TITLE
You cannot pick up or put down objects in manual-mode in enjoy.py 

### ISSUE THREAD

**Issue by jsyedidia** [mila-iqia/babyai#100]
When I run the command
`./scripts/enjoy.py --env BabyAI-BossLevel-v0 --model BOT --manual-mode` 
I cannot pick up or put down any objects manually. I can execute other commands manually like moving or opening doors. If I keep hitting `<RETURN>` to have the BOT execute commands, it picks up objects and puts them down fine. I can pick up objects and put them down fine using
`./scripts/manual_control.py --env BabyAI-BossLevel-v0` with the `<PageUp>` and `<PageDown>` keys, but in `enjoy.py`, the `<PageUp>` and `<PageDown>` keys are being recorded in the terminal, but the action is not taking place.

**Comment by dyth** [comment]
I think pickup and drop have been changed to `p` and `d` (https://github.com/mila-iqia/babyai/pull/99/commits/3b6b3c5356c481a649f5df64bad409117fec86ac)

**Comment by jsyedidia** [comment]
Oh, OK, Thank you. I can adapt. It's a bit confusing that you use `p` and `d` in `enjoy.py` and `<PageUp>` and `<PageDown>` in `manual_control.py`, but you can decide whether you want to change that.

**Comment by maximecb** [comment]
It's because there's no pageup/pagedown keys on some macbook laptops. I'll modify the scripts to support both sets of keys.

**Comment by maximecb** [comment]
@dyth I just opened a small PR if you can quickly review it :)

**Comment by dyth** [comment]
@jsyedidia now you can use both `p`, `d` and `<PageUp>`, `<PageDown>`

**Comment by dyth** [comment]
@maximecb shall we close this?
