### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by wcarvalho** [mila-iqia/babyai#104]
I'm reading through the babyAI paper and I see that the RL sample-efficiency for "GoToRedBallGrey" is ~34. Am I to understand from this that from completing 34 episodes (w/ either success or failure), the agent was able to get a 99% success rate? The code does 64 processes in parallel. Does that mean that after I single iteration of going through the episode once, the agent is able to get 99% success rate? I'm very surprised by this

**Comment by maximecb** [comment]
The numbers are in thousands of episodes.

**Comment by dyth** [comment]
The numbers are indeed in thousands.
