### ISSUE TITLE
Bot bugs (attribute error: prev_carrying)

### ISSUE THREAD

**Issue by Bihaqo** [mila-iqia/babyai#106]
When running the bot on all levels, from time to time I experience the following errors:
`AttributeError: 'Bot' object has no attribute 'prev_carrying'` (bot.py:125)
`AttributeError: 'Bot' object has no attribute 'prev_fwd_cell'` (bot.py:947)

It happens on _some_ episodes e.g. on the level Open or Pickup.

**Comment by maximecb** [comment]
Hi @Bihaqo, can you provide a sample command that reproduces the bug?

**Comment by Bihaqo** [comment]
Oh, sorry, my bad, turned out that I wasn't resetting everything properly in between episodes.
