### ISSUE TITLE
Unable to run PPO agent with arch=bow_endpool_res_pixels

### ISSUE THREAD

**Issue by ayushchakravarthy** [mila-iqia/babyai#109]
Hey!
I am new to DeepRL and am implementing a paper in the BabyAI environment. 
I am trying to run the default ppo algorithm using the train_rl.py script however, I am unable to when I set the flag arch = 'bow_endpool_res_pixels'
The error I get is when the image_conv is applied and says that:
RuntimeError: Given groups=1, weight of size [128, 3, 8, 8], expected input[64, 128, 56, 56] to have 3 channels, but got 128 channels instead
Thanks!

**Comment by dyth** [comment]
Hello!

The arch name convention is `<input>_<config>`.  So if you want to train from pixels, you would have to use `pixels_<config>`, 
  We recommend `pixels_endpool_res`.  Hope this helps!

**Comment by ayushchakravarthy** [comment]
Thank you so much, that worked!
Appreciate the help!
