### ISSUE TITLE
default hyperparameters don't make sense for both IL and RL

### ISSUE THREAD

**Issue by rizar** [mila-iqia/babyai#50]
For example, `--save-interval=1` makes sense for IL but not for RL. `--batch-size=1280` is the one we used for RL, not for IL. 

We should somehow allow these scripts to have different hyperparameters by default.

**Comment by maximecb** [comment]
The `--save-interval` is now different. Dima, do you have a suggestion for an appropriate batch size for IL?

**Comment by rizar** [comment]
For "small" model I used `--batch-size=256`, for "large" model I used `--batch-size=128`. We could switch to using the same batch size for both settings now,  since after the bot was optimized, the demonstrations have become shorter.
