### ISSUE TITLE
GoNextToSubgoal explore bug

### ISSUE THREAD

**Issue by dyth** [mila-iqia/babyai#53]
https://github.com/mila-iqia/babyai/blob/5fbcda6612262d2a18b908b2e1fde727e09f721e/babyai/bot.py#L377

Suggestion to change the following line:

`self.stack` --> `self.bot.stack`
`.get_action()` --> ``

**Comment by maximecb** [comment]
@rizar This seems fairly trivial to fix, just wanted to make sure you are aware of it. It seems like that line of code is simply never exercised during the demo generation?

**Comment by rizar** [comment]
Yeah, apparently this little block of code is simply never executed...

**Comment by saleml** [comment]
It makes sense that this block of code is never executed: The `ExploreSubgoal` is created at line 301 when the bot doesn't know where an object is. But once the position is defined (i.e. starting from line 308), it necessarily means that the bot knows how to get there.

**Comment by dyth** [comment]
Created pull request for fix here: https://github.com/mila-iqia/babyai/pull/58
