### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by jordiae** [mila-iqia/babyai#76]
Hello, thanks for your work.

Would it be possible to run BabyAI on Google Colab? I assume there would be some technical difficulties but perhaps someone has been able to do so.

Thanks in advance.

**Comment by maximecb** [comment]
Hi,

We've never used Google Colab. You'd have to check if you can install the required dependencies: https://colab.research.google.com/notebooks/snippets/importing_libraries.ipynb. Please try it and let us know what happens.

**Comment by jordiae** [comment]
@maximecb Thanks for your answer, I'll give it a try.
