### ISSUE TITLE
Error in docs/train-eval.md?

### ISSUE THREAD

**Issue by ricvolpe** [mila-iqia/babyai#78]
Maybe I am a machine and I do not know this but in **Training** section

> A machine readable log can be found in logs/<MODEL>/log.csv, a human readable in logs/<MODEL>/log.log.

It seems to me that `.csv` is the a human readable log and `.log` is the machine readable log, or am I missing something?

**Comment by maximecb** [comment]
@rizar seems correct?

**Comment by rizar** [comment]
I am bit surprised to hear this. @ricvolpe , could you please give us some snippets of what you see in these logs?
