### ISSUE TITLE
Missing dependency for scikit-build

### ISSUE THREAD

**Issue by dyth** [mila-iqia/babyai#89]
Whilst installing BabyAI with conda on compute-canada, I encounted an error `no module named skbuild` during the very last step `pip install --editable .`.
Some googling revealed that this was caused by a missing package named `scikit-build`, which can installed by `pip install scikit-build`.
Hence this issue could be resolved by adding `scikit-build` to `environment.yaml` under `pip`.

However, I am unsure whether this is caused by an out-of-date version of miniconda on Compute Canada, or a missing dependency in BabyAI or MiniGrid.

**Comment by dyth** [comment]
This seems to be a Compute Canada issue.
I can install BabyAI with no problems at all on my local machine.

**Comment by maximecb** [comment]
You used conda on your local machine?

It might work on your local machine because scikit-build is already installed in your pip environment outside. I think it could be wise to still add it to the yaml file just in case.

**Comment by dyth** [comment]
I did use conda.  Nevertheless, please see #90 for a PR containing this change.

**Comment by maximecb** [comment]
Thanks David
