### ISSUE TITLE
AttGRU model is broken + my quick Fix

### ISSUE THREAD

**Issue by zynos** [mila-iqia/babyai#91]
when i start `train_rl` of the iclr19 branch with:
`--env BabyAI-PickupLoc-v0 --recurrence 20 --memory-dim 2048 --instr-arch "attgru" --tb --procs 64`
(this should be the Large model from your paper)

the program crashes at this line in` model.py`:
```
def forward(self, obs, memory, instr_embedding=None,ret_embed=False):
...
pre_softmax = (keys[:, None, :] * instr_embedding).sum(2) + 1000 * mask

```
with the message
`RuntimeError: The size of tensor a (8) must match the size of tensor b (9) at non-singleton dimension 1`

to fix it i looked into
```
def _get_instr_embedding(self, instr):
...

 if outputs.shape[1] < masks.shape[1]:
                masks = masks[:, :(outputs.shape[1]-masks.shape[1])]
                # the packing truncated the original length
                # so we need to change mask to fit it

            return outputs if self.lang_model == 'attgru' else final_states

```

the line were `masks` is changed has no effect on `outputs`.

So i copied the if statement into the `forward` method and changed
```

        if self.use_instr and self.lang_model == "attgru":
            # outputs: B x L x D
            # memory: B x M
            mask = (obs.instr != 0).float()
            instr_embedding = instr_embedding[:, :mask.shape[1]]
```

to 

```

        if self.use_instr and self.lang_model == "attgru":
            # outputs: B x L x D
            # memory: B x M
            mask = (obs.instr != 0).float()
            # my quick fix stolen from:      self._get_instr_embedding(obs.instr)
            if instr_embedding.shape[1] < mask.shape[1]:
                mask = mask[:, :(instr_embedding.shape[1]-mask.shape[1])]
            #end of my fix
            instr_embedding = instr_embedding[:, :mask.shape[1]]
```
and the program runs again.

Do you think this is sufficient or did i forget something?

Thanks in advance

EDIT:
this error does not occur in BabyAI-PutNextLocal-v0 or BabyAI-GoToLocal-v0
maybe it is specific to BabyAI-PickupLoc-v0

**Comment by maximecb** [comment]
@zynos which version if PyTorch are you using?

@rizar what do you think?

**Comment by zynos** [comment]
@maximecb  i am using pytorch 1.3.1

**Comment by maximecb** [comment]
@zynos would you be so kind as to open a pull request with your proposed changes?

**Comment by rizar** [comment]
Looks like a bug. Will get back to this first thing tomorrow morning.

**Comment by zynos** [comment]
@maximecb done, but i think it should be tested with other environments, it works at least with PutNextLocal
