### ISSUE TITLE
Visualizing stored "images"

### ISSUE THREAD

**Issue by zynos** [mila-iqia/babyai#94]
Question:
I am storing whole episodes in a buffer. Is it possible to visualize the 7x7x3 "images" like you did in the paper?
I want to pass the "image" matrix to a function and get a rendered picture, where I see all the objects and their color like in the BabyAI paper.

Thanks in advance!

**Comment by maximecb** [comment]
Hi @zynos,

There is a function `get_obs_render()` that can be called to produce an image array from an observation:

https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L1212

**Comment by zynos** [comment]
Thanks a lot @maximecb !

in case someone wants to try the same:

```
env = gym.make("BabyAI-PutNextLocal-v0")
renderer = env.render("human")
r=env.get_obs_render(image.cpu().numpy(), 128)
r.toImage().save("testImage", "PNG")
```

`env.render("human")` is necessary for QT otherwise you get the error
 `QPixmap: Must construct a QGuiApplication before a QPixmap`
