### ISSUE TITLE
Publish pip package

### ISSUE THREAD

**Issue by luckeciano** [mila-iqia/babyai#95]
Hello,

I would like to know if the team has plans to publish a pip package for BabyAI anytime soon. It would be very useful to automate installation.

Thanks for the incredible work and support!

**Comment by maximecb** [comment]
Hi luckeciano,

Not at this time, but consider that it is possible to install git repo dependency links using pip. The babyai setup.py from this repo does it: https://github.com/mila-iqia/babyai/blob/master/setup.py#L14
