### ISSUE TITLE
enjoy.py script seems to expect old PyQT version of gym-minigrid

### ISSUE THREAD

**Issue by jsyedidia** [mila-iqia/babyai#98]
I wanted to watch the planning bot solve the Boss Levels, so I ran the command `./scripts/enjoy.py --env BabyAI-BossLevel-v0 --model BOT` and got this error:

```
(babyai) [~/work/babyai] ./scripts/enjoy.py --env BabyAI-BossLevel-v0 --model BOT
Mission: open a yellow door and open the grey door on your right
step: 0, mission: open a yellow door and open the grey door on your right
Traceback (most recent call last):
  File "./scripts/enjoy.py", line 119, in <module>
    if renderer.window is None:
AttributeError: 'numpy.ndarray' object has no attribute 'window'

```

Commenting out the lines

```
    if renderer.window is None:
        break
```
at the bottom of `enjoy.py` made the command work (although closing the window in the GUI caused a problem).

But then I wanted to try manual-mode and I got another error:

```
(babyai) [~/work/babyai] ./scripts/enjoy.py --env BabyAI-BossLevel-v0 --model BOT --manual-mode
Mission: open a yellow door and open the grey door on your right
Traceback (most recent call last):
  File "./scripts/enjoy.py", line 96, in <module>
    if args.manual_mode and renderer.window is not None:
AttributeError: 'numpy.ndarray' object has no attribute 'window'
```

Looking into the code a little more, it seems that `enjoy.py` is expecting an old version of gym-minigrid that was based on PyQT, and that is causing these errors. In fact, if I go back to an old commit of gym-minigrid 
(commit 50f396a9bf39952e5ab1bd13b422f258eb29f954) and re-do `pip3 install -e .` in my gym-minigrid repo using that commit, `enjoy.py` works properly, but unfortunately that old commit of gym-minigrid is incompatible with other scripts like `/scripts/manual_control.py`. 

It looks like `enjoy.py` was never updated after the change to gym-minigrid.

**Comment by maximecb** [comment]
Thanks for pointing this out. I made the refactoring to `gym-minigrid` so we could eliminate the PyQT dependency, because it was often causing issues when installing on clusters or machines without a display attached.

It looks like we forgot to make the necessary changes to `enjoy.py`. For the moment I can point you to the corresponding minigrid script: https://github.com/maximecb/gym-minigrid/blob/master/manual_control.py

I may take a stab at fixing the problem this weekend.

**Comment by maximecb** [comment]
A fix is on the way, I have a pull request in #99. Should get merged shortly, but you can check it out from the PR branch if you're impatient :)

**Comment by maximecb** [comment]
It's merged :)
